services:
  # Serviço Node.js (único)
  - type: web
    name: xmlanalise-node
    runtime: node
    repo: https://github.com/silviobsjunior/xmlanalise
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node index.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: NODE_ENV
        value: production
